/**
 * Writing an investigation's findings back to the ticket as an internal system note.
 *
 * Rules the note obeys:
 * - it is internal (`is_internal = true`), so a student never sees it;
 * - it is attributed to the portal (`author_role = 'system'`, `author_user_id = null`),
 *   never to the staff member who happened to click approve;
 * - it is idempotent: the run id marker makes a second write a no-op instead of a duplicate;
 * - it never changes status, priority or the student-facing conversation. Staff still reply
 *   through the existing support workflow.
 */

import type { SupportMessageRow } from "@/lib/labops/conversation";

const MARKER_PREFIX = "labops-run:";

export function findingsNoteMarker(runId: string) {
  return `[${MARKER_PREFIX}${runId}]`;
}

export type FindingsNoteInput = {
  runId: string;
  findings: string;
  resolution?: string | null;
  model: string;
  /** Absolute or portal-relative link back to the investigation. */
  investigationPath?: string;
};

export type FindingsNote = {
  body: string;
  authorRole: "system";
  authorUserId: null;
  isInternal: true;
};

/**
 * `support_messages.body` is capped at 10,000 characters by a check constraint, so long
 * findings are truncated here rather than failing the insert. The full text stays on the
 * investigation, which the note links to.
 */
const MAX_NOTE_CHARS = 10_000;
const MAX_FINDINGS_CHARS = 6_000;
const MAX_RESOLUTION_CHARS = 2_000;

function clamp(text: string, limit: number) {
  const trimmed = text.trim();

  return trimmed.length <= limit
    ? trimmed
    : `${trimmed.slice(0, limit - 1).trimEnd()}…`;
}

export function buildFindingsNote(input: FindingsNoteInput): FindingsNote {
  const path = input.investigationPath ?? `/admin/labops/${input.runId}`;
  const resolution = input.resolution?.trim()
    ? clamp(input.resolution, MAX_RESOLUTION_CHARS)
    : "";
  const body = [
    `LabOps AI investigation findings ${findingsNoteMarker(input.runId)}`,
    "",
    clamp(input.findings, MAX_FINDINGS_CHARS),
    resolution ? `\nProposed resolution: ${resolution}` : "",
    "",
    `Generated by ${input.model} and reviewed by staff before this note was added. Nothing was`,
    "sent to the student and no ticket field was changed automatically.",
    `Investigation: ${path}`,
  ]
    .filter((line) => line !== null)
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trim();

  return {
    body: clamp(body, MAX_NOTE_CHARS),
    authorRole: "system",
    authorUserId: null,
    isInternal: true,
  };
}

/**
 * True when this run's note already exists on the ticket. Callers check this before
 * inserting, which keeps the note idempotent without a unique index on message bodies.
 */
export function hasFindingsNote(
  messages: readonly Pick<SupportMessageRow, "body" | "is_internal" | "author_role">[],
  runId: string,
) {
  const marker = findingsNoteMarker(runId);

  return messages.some(
    (message) =>
      message.is_internal &&
      message.author_role === "system" &&
      message.body.includes(marker),
  );
}
